data:
  train_bi: D:\iwslt17\bi\train_bi.jsonl
  dev_en_de: D:\iwslt17\bi\dev_en-de.jsonl
  dev_de_en: D:\iwslt17\bi\dev_de-en.jsonl
  test_en_de: D:\iwslt17\bi\test_en-de.jsonl
  test_de_en: D:\iwslt17\bi\test_de-en.jsonl
  spm_model: D:\iwslt17\bi\spm.model
special_ids:
  pad_id: 0
  bos_id: 1
  eos_id: 2
  unk_id: 3
  lang_tag_en: <2en>
  lang_tag_de: <2de>
model:
  d_model: 512
  nhead: 8
  dim_ff: 1024
  num_encoder_layers: 3
  num_decoder_layers: 3
  dropout: 0.1
  share_embeddings: true
  tie_softmax: true
  max_src_len: 128
  max_tgt_len: 128
train:
  seed: 3407
  epochs: 10
  batch_size: 64
  lr_factor: 2.0
  warmup_steps: 4000
  label_smoothing: 0.1
  grad_clip: 1.0
  amp: true
  log_every: 200
  save_dir: D:\iwslt17\runs\shallow
infer:
  max_gen_len: 128
  beam_size: 1
  lenpen: 0.6
logging:
  epoch_sample_n: 2
